### ISSUE TITLE
Should we stop relying on github pages to avoid 404s?

### ISSUE THREAD

**Issue by smarter** [lampepfl/bench#474]
Whenever the bot announces a new benchmark result for a PR, we need to wait some amount of time before the page actually works, until then we just see a 404. I assume this is because we rely on github pages which takes some time to generate pages. Could we move to hosting these pages ourselves on an EPFL machine instead?

**Comment by liufengyun** [comment]
Yes, that's a possibility. Hosting on Github pages causes some other inconvenience: we cannot bind EPFL domain name to Github servers due to EPFL regulations --- we have to embed the page in an `iframe`.

**Comment by liufengyun** [comment]
Close now, as https://dotty-bench2.epfl.ch is hosted on EPFL machines.
